# Generated by Django 4.1.1 on 2023-01-27 02:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='pdf_files/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
