# Generated by Django 4.1.1 on 2022-09-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.FileField(default=0, storage='digitalproducts', upload_to=''),
            preserve_default=False,
        ),
    ]
