# Generated by Django 4.1.1 on 2022-09-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdf',
            field=models.FileField(storage='digitalproducts/%Y/%m/%d', upload_to=''),
        ),
    ]
