# Generated by Django 4.1.1 on 2022-09-24 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pdf',
        ),
    ]
