# Generated by Django 4.1.1 on 2022-09-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='pdf_files/%Y/%m/%d'),
        ),
    ]
