# Generated by Django 4.1.1 on 2023-01-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='default.jpeg', upload_to='blog_images/'),
        ),
    ]
