# Generated by Django 4.1.1 on 2023-02-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_body_alter_post_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
