# Generated by Django 4.1.1 on 2023-02-12 20:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_post_image_post_post_header_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_images',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
