# Generated by Django 4.1.1 on 2023-02-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.TextField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
