# Generated by Django 4.1.1 on 2023-02-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.TextField(default='0', verbose_name=0),
        ),
    ]
