# Generated by Django 4.1.1 on 2023-02-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_post_time_alter_post_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='post_categories',
        ),
        migrations.AddField(
            model_name='post',
            name='post_desc',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
