# Generated by Django 4.1.1 on 2023-02-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_tags_post_post_categories_post_post_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_desc',
            new_name='post_description',
        ),
    ]
