# Generated by Django 4.1.1 on 2023-03-31 23:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_images',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
