# Generated by Django 4.1.1 on 2023-04-05 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insightsTwo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trailing_pe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forward_pe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trailing_ps', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forward_ps', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrq_pb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pcf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quick_ratio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_ratio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_debt_to_equity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_debt_to_capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bv_mv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ass_turnover', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inv_trnover', models.DecimalField(decimal_places=2, max_digits=10)),
                ('op_margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prof_margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ev_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ev_ebitda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('sector_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='insightsTwo.sectorname')),
            ],
            options={
                'verbose_name_plural': 'Weekly Stats',
                'ordering': ('sector_name',),
            },
        ),
    ]
