# Generated by Django 4.1.1 on 2023-04-06 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insightsTwo', '0002_weeklystats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklystats',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
