# Generated by Django 4.1.1 on 2023-04-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightsTwo', '0003_alter_weeklystats_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklystats',
            options={'ordering': ('-date_created',), 'verbose_name_plural': 'Weekly Stats'},
        ),
        migrations.AlterIndexTogether(
            name='weeklystats',
            index_together={('sector_name', 'date_created')},
        ),
    ]
