# Generated by Django 4.1.1 on 2023-04-15 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insightsTwo', '0004_alter_weeklystats_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklystats',
            name='forward_ps',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='IndustryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('industry_image', models.ImageField(blank=True, upload_to='industry_images')),
                ('sector_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_name', to='insightsTwo.sectorname')),
            ],
        ),
        migrations.AddField(
            model_name='weeklystats',
            name='industry_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='industry', to='insightsTwo.industryname'),
        ),
    ]
