# Generated by Django 4.1.1 on 2023-04-17 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insightsTwo', '0005_alter_weeklystats_forward_ps_industryname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industryname',
            options={'ordering': ('industry_name',)},
        ),
        migrations.AlterIndexTogether(
            name='industryname',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='weeklystats',
            index_together={('industry_name', 'date_created')},
        ),
    ]
