# Generated by Django 4.1.1 on 2023-07-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insightsTwo', '0007_alter_weeklystats_ass_turnover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklystats',
            name='ass_turnover',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='bv_mv',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='current_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='ev_ebitda',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='ev_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='forward_pe',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='forward_ps',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='gross_margin',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='inv_trnover',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='mrq_pb',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='op_margin',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='pcf',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='prof_margin',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='quick_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='roa',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='roe',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='roic',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='total_debt_to_capital',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='total_debt_to_equity',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='trailing_pe',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='weeklystats',
            name='trailing_ps',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
    ]
