# Generated by Django 4.1.1 on 2023-07-24 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insightsTwo', '0008_alter_weeklystats_ass_turnover_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industryname',
            options={'ordering': ('industry_name',), 'verbose_name': 'industry_name', 'verbose_name_plural': 'industry_names'},
        ),
        migrations.AlterModelOptions(
            name='sectorname',
            options={'ordering': ('sector_name',), 'verbose_name': 'sector_name', 'verbose_name_plural': 'sector_names'},
        ),
        migrations.AlterField(
            model_name='industryname',
            name='sector_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_to_industry', to='insightsTwo.sectorname'),
        ),
    ]
