# Generated by Django 4.1.1 on 2023-07-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insightsTwo', '0009_alter_industryname_options_alter_sectorname_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryname',
            name='industry_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
